<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ConcatWebServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ConcatWebServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ConcatWebServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://ws.concat/">
    <import location="http://localhost:8080/ConcatService/ConcatWebService?wsdl" namespace="http://ws.concat/"/>
    <plnk:partnerLinkType name="ConcatWebServiceLinkType">
        <plnk:role name="ConcatWebServiceRole" portType="ns:ConcatWebService"/>
    </plnk:partnerLinkType>
</definitions>
